after_success:
  - npm run coveralls

before_script:
  - npm i -g eslint
  - eslint .

language: node_js

node_js:
  - 6
  - 7
  - 8
  - 9

notifications:
  slack:
    rooms:
      - secure: "X0Pzylgg3wWX+04f4Mnl7o5DCFgrYgWZ1qL2LicDmJ2tlrqFx1CemsRV1BLy70MDIWo6DtzrJkP5dCMnpRtJo1w/ehFbbJ0ZHYVS2BKVbzyy2UorPXHaB9hyS2sVswTJP0HDlEgwbkMOrx8jvvKUyWqlcP2U0D3ZlAKpINfY3EM="
    on_success: always

services:
  - redis-server
